### ISSUE TITLE
Pin the gem versions in the Gemfile

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1042]
The gems are unpinned.  I can submit a pull request to update them.

**Comment by andrew** [comment]
No thanks, that’s what the Gemfile.lock is for

**Comment by jhsu802701** [comment]
If you don't pin the gems, the "bundle upgrade" command upgrades everything.  I find it best to break the upgrading process into smaller steps, and that requires pinning gems.  Trying to upgrade everything all at once means a greater risk of issues, and the fact that so many changes were made makes it difficult to troubleshoot things.  Breaking up the process into smaller steps makes it much easier to troubleshoot when things go wrong.

**Comment by andrew** [comment]
We keep our dependencies up to date automatically with dependabot, so currently everything is running on the latest version and we’re able to upgrade whenever a new release of a gem comes out. 

`bundle outdated` can show you which dependencies are out of date and individual ones can be updated with `bundle update gemname` rather than having to update all dependencies at once. 

The Gemfile versions should be used to specify incompatible ranges and always combined with a good known working set of of locked versions in Gemfile.lock that you can rollback to if the upgrade doesn’t work out.
