### ISSUE TITLE
Load event data without using GitHub App

### ISSUE THREAD

**Issue by jryans** [octobox/octobox#1254]
### What feature you'd like to see

I would like to be able to load the "enhanced notification" data without requiring the GitHub App for this.

## Motivation

In my [comment](https://lobste.rs/s/14jg2c/untangle_your_github_notifications_with#c_tvfbjz) on Lobsters, I thought Octobox did not support additional data like CI status, etc. for issues and PRs, but in fact it does... it just requires the GitHub App. In fact, I had already installed the GitHub App for my personal account, but that is not of much use to me, because most repos I am interested in tracking occur in other organizations that I don't control, and so I can't install the app there even if I wanted to.

## Pitch

Instead of using the GitHub App for enhanced notification data, use some other means, such as the Events API. GitHub Apps are fine for pricing Octobox in general, but it blocks access to enhanced data for repos where it can't be installed.

**Comment by andrew** [comment]
@jryans if you run your own instance of Octobox you can set [`FETCH_SUBJECT=true`](https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#downloading-subjects) which will add `repo` scope to the oauth app login, enabling Octobox to sync extra data from issues and pull requests, including CI status.

The main thing you loose not using a GitHub App is the webhook to get notified of when those events occur, you could implement something to poll the event timeline for each repo on a regular basis but then you might as well just set up a cron job to sync your notifications more frequently, docs here: https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#cronjob

**Comment by jryans** [comment]
Aha, thanks for the quick reply! I'll give these things a try. 😁 Sorry for not looking at the docs more closely; I wasn't expecting it to be covered by an installation option.

**Comment by coreyja** [comment]
@andrew I am running into a similar issue and wanted to try commenting here, before I made my own Issue!

I am running Octobox on my own instance, and for most of the same reasons @jryans mentioned, I am using a Personal Access token for the oauth, so that it can access the Repos that are owned by the organization.
I also have the `FETCH_SUBJECT=true` flag, and it was working beautifully before this weekend.

This weekend I 'upgraded' to using a GitHub App. It only has access to my Personal repos, and for those it is working perfectly!

However all my repos under 'The Org' aren't getting any of the extra meta-data they used to. The one that is the most important to me is the PR status icon, which is currently just the white icon.

Is it possible/does Ocotobox already fall back to trying the `FETCH_SUBJECT` if there is a GitHub app installed, that simply doesn't have permissions to access all my repos?

Does this sound like a code issue to you? And if so do you have an idea where the offending code might live? I am more than happy to take a look and try to get a PR out if this is a real bug!

Also let me know if you would like this as a separate issue, and I will move it over!

**Comment by andrew** [comment]
@coreyja that sounds like the personal access token isn’t being used where it should be, a code path that I’ve not tested much, can you bump that comment to a new issue as I’d say it’s a bug

**Comment by coreyja** [comment]
Done! Copied to its own issue here! https://github.com/octobox/octobox/issues/1261
