### ISSUE TITLE
When does notifications open in thread view?

### ISSUE THREAD

**Issue by evexoio** [octobox/octobox#1384]
### Summary of Problem

- What are you trying to do?
I'm trying to open notification in the thread view in octobox
- What happens?
I get redirected to github notification url
- What should have happened?
thread view open and notification info appear

### Steps to Reproduce the Issue
Go to settings, switch the notifications view to 'Octobox' and go back to inbox, all notifications still open in github and not octobox

**Comment by BenJam** [comment]
Confusingly only /some/ notifications will open a thread. Not every notification has a thread (they're called subjectable in code) and sometimes we'll have the notification but we'll have the subject (which contains the comments) in a queue awaiting download. In order to make the behaviour more obvious we place the 'external link' icon next to notifications that'll open in GH instead of Octo. 

We'll be putting more time and attention into threads in the new year, which is why it's currently in 'beta'. If you've got any ideas or feedback about what you like/dislike then let us know in a new issue 👍

**Comment by BenJam** [comment]
initially I replied about only some notifications opening in GH (which is as it should be at the moment) but then I re-read

> all notifications still open in github and not octobox

Ah.

**Comment by BenJam** [comment]
@evexoio I believe the problem here is that you have not enabled comments in your `.env` file. In order to do so you need to include:

```
FETCH_SUBJECT=true
INCLUDE_COMMENTS=true
```

As thread-view is currently in beta those instructions are not in the installation documents. If this isn't the case or you include the above and kick of syncing with:

`Notification.subjectable.find_each{|n| n.update_subject(true); }`

**Comment by kfstorm** [comment]
@BenJam I cannot find notifications view in settings and I've set the env variables you mentioned above. What's wrong? I use the latest docker image.

**Comment by kfstorm** [comment]
Never mind. I only added env variables to `.env` file and forgot to update `docker-compose.yml` to reference these env variables.
