### ISSUE TITLE
Not every issue shows comments/labels/status

### ISSUE THREAD

**Issue by kbaley** [octobox/octobox#1581]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

🐞 **Problem**
In any list of issues, roughly half of them don't show how many comments there are on the issue/PR nor do they show an author or a green/red/purple icon indicating its status (an icon is always shown but for these issues/PRs, it's black).

This carries over to the Open/Merged/Closed filters. Issues/PRs that don't have a coloured icon don't show up in any of these filters.

🎯 **Goal**
Consistency in the UI. I'm most interesting in being able to see at a glance which issues/PRs are merged/closed and I'd like to use the corresponding filters.

💡 **Possible solutions**
I haven't seen a pattern to the ones that are affected. Perhaps related to the GitHub API rate limit?

📋  **Steps to solve the problem**

**Comment by BenJam** [comment]
@kbaley I believe you might be experiencing the expected behaviour: we only support these features on open source repos for free. To get them for all repos you'd need to either run your own installation or pay for a individual subscription (and install the GH app on each repo you wish to see this information for). More information at https://medium.com/octobox/walking-the-tightrope-charging-for-private-repos-on-octobox-io-6efe79662479

**Comment by kbaley** [comment]
Thanks @BenJam. I think that's probably it. I do have a paid individual subscription and I'm seeing the notifications show up on certain private repos but not all. And I did confirm that Octobox is showing up in the list of integrations for the ones that work.

But I'm not sure where I'm supposed to install it on the other repos. In my settings, I have "All repositories" selected for Repository Access. However, in the list of options for "Only select repositories", I see only my personal repos and not the others I have access to.

**Comment by kbaley** [comment]
All figured out now. Got it sorted.
