### ISSUE TITLE
Use media accepts header to get github to render markdown of comment body

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1800]
When downloading comment bodys from the github api, we can send a media query to request that github flavoured markdown is sent, that means we don't need to keep up with any extra features they add to their rendering engine: https://developer.github.com/v3/media/#comment-body-properties

**Comment by BenJam** [comment]
Bit confused: do you mean grabbing the html rather than raw?

**Comment by andrew** [comment]
@BenJam yep 👍

**Comment by BenJam** [comment]
just having a think about how best to limit the size of the DB and manage the queue as we sync html versions of commen threads we already have. 

For new comments it's easy, store the html version (adding `body_html' to the model) instead of the text 'body' that's already there.

What I'm thinking then is maybe we add (to a seperate, lower priority queue in sidekiq if needed) a job that goes and re-syncs that subject's comments when we see a new notification for that subject, *replacing* `body` with `body_html`.

I can imagine that the transition will be a little ugly, with some threads showing newer comments in HTML and older in plain text, but that seems better than trouncing queues and impacting users. 

LMK if you feel any different @andrew.

**Comment by andrew** [comment]
Good point, I forgot that we do that for comments, will make it a little more nasty, but in the end it means we don't need to keep up with whatever special markup features github adds so it'll save lots of work in the long term.
