### ISSUE TITLE
Suggestion: color icons to indicate state of issues/PRs

### ISSUE THREAD

**Issue by bnjmnt4n** [octobox/octobox#210]
Using colors like GitHub's own UI would be really great to easily see the status of issues/PRs.

**Comment by andrew** [comment]
@demoneaux unfortunately we can't get the state of the issues/prs without doing #4 which is pretty involved

**Comment by Soleone** [comment]
this would be amazing! i unfortunately get a lot of noise in my octobox for notifications that are basically just "this just merged". or when i'm like a week away and come back to inbox 100+ i would like to see the ones that already merged/closed because they're not very actionable any more.

to put this into perspective i get around 20 notifications every day. so any notification that is not really actionable for me goes a long way.

**Comment by andrew** [comment]
First part of this has been merged in #411 and is available behind the `FETCH_SUBJECT` env var feature flag, docs here: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects

Still working on getting it available on https://octobox.io

**Comment by andrew** [comment]
Closing this as #4 has shipped, just waiting on #472 for it to be enabled on https://octobox.io
