### ISSUE TITLE
New Read notifications aren't synced

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#241]
I believe this is a regression that's come about since https://github.com/octobox/octobox/pull/227

If open an issue and it receives a comment that I see in the web view (which marks it as read on GitHub), then octobox never syncs that issue. This mean that notification falls through the cracks again, very annoying.

**Comment by WillAbides** [comment]
I'm a bit lost on why [fetch_read_notifications](https://github.com/octobox/octobox/blob/5aee3acbc35bb9a9cf1887819d0c121a2d5265b9/app/models/notification.rb#L99-L107) doesn't catch this.  Octobox still sees the notification as unread, so the since parameter on that query should be at least one second before the notification's previous `updated_at` time.  What am I missing here?

**Comment by andrew** [comment]
I think this is fixed by https://github.com/octobox/octobox/pull/451
