### ISSUE TITLE
Auto sync

### ISSUE THREAD

**Issue by GiacomoLaw** [octobox/octobox#270]
Instead of manually updating it, auto synchronising every so often would be great.

**Comment by GiacomoLaw** [comment]
Just seen this:

https://github.com/octobox/octobox/blob/34c487d160c0826f6457d11fbe2479ac3758cce6/README.md#sync-notifications-automatically

Does it do this on octobox.io?

**Comment by WillAbides** [comment]
I think that #200 is actually closer to what you want because it will update a loaded page instead of just running in the background.  Unfortunately neither of these are running on octobox.io.

Looking back at #200 I realize I neglected to update README.

**Comment by GiacomoLaw** [comment]
@WillAbides I'll add that it doesn't auto sync on the hosted version.

**Comment by GiacomoLaw** [comment]
Here is the README.md update: https://github.com/octobox/octobox/pull/271

**Comment by GiacomoLaw** [comment]
Here are two potential fixes:

- https://github.com/octobox/octobox/pull/275
- https://github.com/octobox/octobox/pull/274

**Comment by WillAbides** [comment]
I added doc for #200 here:  https://github.com/octobox/octobox/blob/master/README.md#allowing-periodic-notification-refreshes

I don't think that #274 or #275 add anything to isn't already there, but they do force a periodic page refresh on all users instead of making it optional.  I know that @andrew is opposed to forcing refreshes on users.

**Comment by GiacomoLaw** [comment]
@WillAbides I think an option should be added, if someone could add that it would really be appreciated. I'm not good enough at ruby to do that. Sorry!

**Comment by WillAbides** [comment]
@GiacomoLaw: It's not a matter of adding any new code.  Unless I'm missing something significant, I think Octobox already does what you want if it is enabled on the server.

So you can either self-host octobox or lobby @andrew to set `MINIMUM_REFRESH_INTERVAL` on octobox.io.

**Comment by GiacomoLaw** [comment]
Okay, cool. Surely and option could be added?

**Comment by chrisarcand** [comment]
> Okay, cool. Surely and option could be added?

@GiacomoLaw IIRC These options are disabled due to a current desire to *not* store user authentication details (understandable). Some work should be done before this option is enabled, at least (I think it's currently stored in plaintext). 

I would suggest self-hosting for now. A 'hobby' tier (free) on Heroku is enough to meet your needs and is easy to set up (I use this, and haven't had any need to upgrade it yet). 

> About self hosting, I find that it's public on Heroku, and I can't update from this repo.

Sorry, I don't understand what you mean here.  😕

**Comment by andrew** [comment]
As @WillAbides mentioned, this option is already available via the `MINIMUM_REFRESH_INTERVAL` ENV variable if you run octobox yourself but at the moment I'm not prepared to turn it on for my hosted version on https://octobox.io, that may change in the future but for now I'm going to close this issue.
