### ISSUE TITLE
Configuration API

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#280]
I'd like to write a simple configurator to allow people to configure the application in a single convenient spot, with more flexibility, rather than the bucket of environment variables that we currently have.

I was thinking a configuration block available from the top namespace; we can then gitignore a specifically named initializer that people can add to configure their box how they want without tracked code changes.

A few questions up for discussion:

Concerning current environment variables...
* Can some of the current environment variables be immediately removed?
* If they can't be, should they be deprecated? (add a warning wrapper that will yet at you if you use them, say that they'll be removed 'eventually'?)
* Or, should we just keep the existing ones any new configuration settings will just have a configurator option with no env var option?

Lastly, if some variables *are* removed/deprecated, are there any current ones which, even if you think there was a configurator option, you'd still really like to see as an environment variable? I haven't used the personal access token feature, but perhaps that one is nice to just be able to do without writing any new file (unsure).

**Comment by andrew** [comment]
The nice thing about the current ENV setup is that you can deploy an instance of octobox to heroku using the heroku app button without having to fork the project or even have any coding experience.

Perhaps we can have a configuration file that overrides ENV vars if it's been customized otherwise acts like a heroku deployment, similar to database.yml in rails

**Comment by chrisarcand** [comment]
I should also add, we have the beginnings of what I was envisioning with https://github.com/octobox/octobox/blob/2a965cf54372639d66dc3595986bee5abe98b78d/config/initializers/octobox_config.rb

**Comment by WillAbides** [comment]
I really like config through environment variables*, and want to continue the ability to set config through the environment.  That said, I am not opposed to having additional config methods as long as everything can continue to be set through environment variables as well.

I added `octobox_config.rb` to abstract the config from the details of how config options are set.  Even if we only ever use environment variables, it helps keep the code dry, but if you use it as a basis for a config api, that's all the better.

* Instead of making my own argument for environment variables, I'll just refer to this: https://12factor.net/config

**Comment by chrisarcand** [comment]
> without having to fork the project

That's part of the intent here; I'd like to be able to do more customization via an API without code tracked code changes. See also, database.yml

> ... or even have any coding experience

Ah that's a fair point. I guess you would need to know basic Ruby stuffs to get full use of things. I'd argue if you're looking to customize your own hosted version of the application you'd need to learn that anyway, but I respect your wanting to make it as configurable as possible for anyone immediately. 

Good link @WillAbides 👍  Since I've worked on code that's set in releases I've sort of lost track of some best practices for live apps 😅 

We can continue to do how the above config file behaves (which is exactly what you suggest), in that case 💙 I'll just do a little cleanup, allow for untracked configuration as an option, etc. and keep the core of what you've said here. 

Thanks!

**Comment by WillAbides** [comment]
@chrisarcand: Can you clarify what you mean by API here?  I've been reading this as meaning API in the broad since, but I occurs to me that you may be talking about something like a RESTful API.  And do you want to change configuration on a running instance or would settings still be immutable for the instance?

**Comment by chrisarcand** [comment]
@WillAbides Nope, you were right, API in broad sense. Given our conversation above these changes should be be considered 'refactoring the current config file (still allowing for all env vars), allowing a gitignored initializer, and pointing the few scattered env var refs in existing code to go through the config object)

I'll shut up and show some code, you won't hate it :D

**Comment by WillAbides** [comment]
@chrisarcand: After my most recent PR, `octobox_config.rb` is starting to get a bit more logic in it than I would like.  I'd like to refactor it to move the logic into `/lib` where it is more testable.  Does this jibe with the refactor you are working on?

I'm happy to do that part of the refactor myself or let you do it.  I just don't want to be working on branches that are going to massively conflict.

**Comment by chrisarcand** [comment]
@WillAbides PR coming in about 15 minutes :) I'll ping.

**Comment by chrisarcand** [comment]
And yeah that's pretty much exactly what I so poorly tried to explain above 💙
