### ISSUE TITLE
Get a "Message" or "Entry" for any activity on Repos I Own / Watch?

### ISSUE THREAD

**Issue by gauntface** [octobox/octobox#324]
I'd love it if I could have a way to say "Any activity on this repo I want to land in octobox" for example new issues, PR's - anything.

Is this possible or something that could be implemented?

**Comment by tarebyte** [comment]
Basically what you're asking for is a subscribable events thread for Octobox.

While it is possbile to get events either through the [pulling the API](https://developer.github.com/v3/activity/events/) or from [Webhooks](https://developer.github.com/webhooks/) I don't think it's something we'd want to support on Octobox proper.

**Comment by chrisarcand** [comment]
> for example new issues, PR's - anything.

I don't know if I'm misunderstanding, but I don't see how that isn't exactly what Octobox does... I subscribe to repos that I own and repos that I watch on Github and I get notified for every new issue, pull request, or comment on the repo in Octobox. 

Is there some specific event that you're looking for that you haven't mentioned above?

There are some events that occur that aren't picked up by Octobox because they aren't a part of the Notifications API for Github - an example is when a commit is pushed to a branch/pull request. In that case, I agree with @tarebyte in that it's something currently beyond the scope of Octobox proper.

**Comment by gauntface** [comment]
@chrisarcand I'm not seeing entries for repos that I own. I only get entries for issues, PRs etc that I'm tagged in. I have set something up wrong on octobox.io that's caused this behavior?

At the moment I'm planning on adding templates for all repo's to try and account for the behavior I'm currently seeing.

**Comment by tarebyte** [comment]
@chrisarcand are you watching your own repos?

You may have have this setting turned off

<img width="769" alt="screen shot 2017-03-03 at 13 26 12" src="https://cloud.githubusercontent.com/assets/564113/23563524/05f5ee18-0015-11e7-9834-75f81ca0a62f.png">

You can find it that settings box here: https://github.com/settings/notifications

**Comment by gauntface** [comment]
@tarebyte that could easily be where I was going wrong - my watching was only marked for email - so added web to that and will try Automatically watch if that doesn't do (I'm part of a number of orgs with lots of repos being generated I don't care about so hopefully watch will do it :) )

Thanks for the info - will close this issue for now.
