### ISSUE TITLE
Native Mac Desktop notifications?

### ISSUE THREAD

**Issue by ljharb** [octobox/octobox#378]
I'd love to tie this into my native Mac OS notification framework.

**Comment by andrew** [comment]
We currently don't have any form of push notifications but you can configure it to poll for new messages which could emit some kind of notification when a new/updated item comes in

**Comment by andrew** [comment]
Going to close this for now as I can't see us doing it in the short term, but if anyone really wants it and is willing to have a go at implementing it then drop a comment and we'll open it back up.

**Comment by jondkinney** [comment]
Love Octobox! Just trying to figure out what my workflow will be. I head up a dev team at a consultancy, so I have a lot of repos I'm helping watch and review. Email was not working for me, so I turned off those notifications. But now I have to manually remember to go to octobox and refresh every so often. I'd like to keep a pulse on things through notification center so that if someone pings me for a review that is urgent I can see it and respond and triage through octobox. So 👍 for this feature!
