### ISSUE TITLE
Code Owner "Review requested" notification incorrectly categorized as "Mention"

### ISSUE THREAD

**Issue by davidcelis** [octobox/octobox#400]
I recently received a notification in Octobox that was shown to me as a Mention:

![](https://cdn.davidcel.is/screens/Screen-Shot-2017-07-07-12-09-35.png)

However, when I click through to the notification's source, a pull request, I wasn't directly @mentioned. Instead, there was a review requested from a team that I am a member of:

![](https://cdn.davidcel.is/screens/Screen-Shot-2017-07-07-12-11-42.png)

I have a feeling that this has to do with the new [Code Owners](https://github.com/blog/2392-introducing-code-owners) feature, as that is why my team's review was requested.

**Comment by andrew** [comment]
@davidcelis we don't change the `reason` field value that comes in from the Notification API in Octobox which leads me to believe that it's the GitHub API returning the wrong value.

Looks like the ["Reasons"](https://developer.github.com/v3/activity/notifications/#notification-reasons) section of the API docs haven't been updated since that blogpost, perhaps you'd be able to raise it internally?

**Comment by davidcelis** [comment]
You're right, this _is_ a GitHub bug 😅

**Comment by chrisarcand** [comment]
![](http://gifs.chrisarcand.com/picard-laughing.gif)

**Comment by andrew** [comment]
Ran into this bug today too, looks like if someone leaves any kind of comment with their review, the notification shows it as a mention and links to it as if it's a comment with no `pull_request_review_id` present, definitely a bug on the Github end, @davidcelis any word on a fix?
