### ISSUE TITLE
Feature: Unsubscribe from Repos

### ISSUE THREAD

**Issue by paulcbetts** [octobox/octobox#406]
It'd be great if Octobox would let you Unsubscribe from all repos in the current view - i.e. whatever I've got selected, I want to be able to say, "Unsubscribe to all these repos", or at least be able to unsubscribe to An Entire Org, then resubscribe to a specific repo in that Org.

I want to be able to use Octobox to undo some of the damage of "Automatically Subscribe to new repos in this org" from Atom :)

**Comment by andrew** [comment]
I don't think this makes sense to have in Octobox at the moment, the GitHub API makes it really slow to unsubscribe from multiple things and we don't really have a place for it in the UI right now, going to close this issue but feel free to make a counter argument if you really think it's important.

**Comment by maxandersen** [comment]
i just want to second this - or at least have a link to goto relevant page on github to do the unsubscribe.

I over time now have hundreds of repos i'm subscribed to just because I was (or is) admin on the org level - for now I have survived by scripting me out of subscriptions. would be nice if octobox would let me just click a button and forget instead ;)

**Comment by andrew** [comment]
Agreed, I think it makes sense to add this into Octobox now so reopened 👍
