### ISSUE TITLE
what exactly is smart shutdown?

### ISSUE THREAD

**Issue by cyberhck** [octobox/octobox#419]
Today when I came back to my PC and wanted to sync my notification, I found out that octobox was down. (I'm using docker, I use octobox executing `docker-compose up`)

Going through logs (I don't run with `docker-compose up -d`) in `stdout`, it says

> database_1  | LOG:  received smart shutdown request
> database_1  | LOG:  autovacuum launcher shutting down
> app_1       | [1] - Gracefully shutting down workers...
> database_1  | LOG:  shutting down
> database_1  | LOG:  database system is shut down
> app_1       | [1] === puma shutdown: 2017-08-24 05:29:10 +0000 ===
> app_1       | [1] - Goodbye!
> app_1       | Exiting
> 

I have no recollection of doing that, I haven't clicked anywhere, AND, I haven't done anything unusual, I always suspend my PC, go home, come back next day, it worked every single day, not sure what happened today.

Can anyone tell me what is this smart shutdown?

**Comment by chrisarcand** [comment]
That exact line is from your database - specifically, PostgreSQL. It's part of a normal shutdown. That's followed by lines from the Puma web server also shutting down.

Why your system application was told to shut down we'll be unable to tell from here, but it is very unlikely to be anything to do with Octobox, so I'm going to close this. Feel free to reopen if you find otherwise. Thanks!

**Comment by cyberhck** [comment]
okay, I also did some google and it said it's related to pgsql, I'm just curious why it shut down, because I never sent a SIGKILL, I always press `Ctrl + C` when I want to stop docker-compose, and I didn't do that, anyway, thanks for an instant response.

**Comment by chrisarcand** [comment]
No problem! Good luck!
