### ISSUE TITLE
Automatically refresh on first load

### ISSUE THREAD

**Issue by Floppy** [octobox/octobox#496]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
On load, the user has to click refresh every time. This isn't very nice UX. Auto-refresh is already availble (#200), but not on octobox.io.

🎯 **Goal**
Improve the UX when loading octobox.io

💡 **Possible solutions**
Could the refresh be auto-triggered on page load? Would that be reasonable on servers where autorefresh is disabled? I *suspect* it would just automate behaviour that users already do by hand, so cause very little extra load.

**Comment by andrew** [comment]
@Floppy how would you define first load? It's not a single page web app so every action is basically a page load

**Comment by Floppy** [comment]
Good point. It feels like a SPWA, so I forgot it wasn't. Perhaps a cookie then to auto-refresh if it wasn't done for (say) an hour.

**Comment by garrettw** [comment]
I have this issue on my own instance too. When I first load the page, I would expect it to go ahead and fetch the latest data from GitHub, but it doesn't. It comes up empty saying it last updated the last time I had it open. I think it should come with fresh data when I open it up.

**Comment by andrew** [comment]
This still needs fixing but FYI auto-refresh is [now available](https://github.com/octobox/octobox/commit/f9b640ea5d0850dbe98cab6bf3cd2071d109d158
) on https://octobox.io, you can enable it from https://octobox.io/settings:

![screen shot 2018-08-10 at 16 23 44](https://user-images.githubusercontent.com/1060/43966472-ea0ddf1a-9cb9-11e8-801c-f6d2a0209278.png)

**Comment by pradyunsg** [comment]
IIUC, we only want this to execute on the first load of the root page. If so, I think we can do something like the following injected inline into `/` (from https://github.com/turbolinks/turbolinks/issues/115#issuecomment-226316428):

```js
document.addEventListener("turbolinks:load", function(event) {
  if (!event.data.timing.visitStart) {
    // Initial page load
    sync_notifications();
  }
})
```

See also: https://github.com/turbolinks/turbolinks/pull/286

**Comment by bajtos** [comment]
Hello 👋 and sorry to hijack/revive this old thread.

When I started to use `octobox.io` some months ago, data from GitHub was automatically synced for me. Recently, this is no longer true and I have to always press the refresh button to get my notifications updated.

<img width="287" alt="Screen Shot 2020-02-07 at 14 54 16" src="https://user-images.githubusercontent.com/1140553/74035012-bd2f6a00-49b9-11ea-89c1-df60497292cb.png">

I find that rather cumbersome, because sometimes I forget to refresh and then I miss new notifications :(

According to https://github.com/octobox/octobox/issues/496#issuecomment-412116768, it used to be possible to configure auto-refresh on https://octobox.io/. However, I don't see that option in the Settings page anymore.

Please advise, how can I get auto-refresh to work?

**Comment by andrew** [comment]
@bajtos I had to turn off the automatic syncing as there were way too many free users on the hosted version of Octobox and it was costing huge amounts. Auto-refresh is also turned off on the hosted version because the implementation was buggy and kept bringing the server down!

Actually solving this issue (sync on first load) would be great so thanks for bringing it up again, I'll have a think about a way to solve it over the weekend.

**Comment by bajtos** [comment]
>  I had to turn off the automatic syncing as there were way too many free users on the hosted version of Octobox and it was costing huge amounts. Auto-refresh is also turned off on the hosted version because the implementation was buggy and kept bringing the server down!
> 
> Actually solving this issue (sync on first load) would be great so thanks for bringing it up again, I'll have a think about a way to solve it over the weekend.

Thank you @andrew for a timely response ❤️ I can see how it could be difficult to support auto-refresh for people using the free tier. For the record, I am a paying user myself.

Would it perhaps be an option to enable automatic syncing, auto-refresh or sync-on-first-load for paying users only? It may become a good incentive to nudge people towards a paid plan.

From my perspective as a user, I can live with a semi-automatic syncing. For example, if notifications could be automatically synced once an hour without requiring me to press any buttons, then that would be much better than no syncing at all.

Anyhow, those are just few ideas to consider. Thank you for running such a helpful service!

**Comment by andrew** [comment]
@bajtos good call, I've re-enabled auto-syncing for paying customers on octobox.io

**Comment by bajtos** [comment]
@andrew it seems like auto-syncing is no longer working, could you please check?

**Comment by andrew** [comment]
As far as I can tell it's still working again for you now, looks like you hadn't logged out and back in in over a month which may be an issue with a recent change I made: https://github.com/octobox/octobox/commit/d2e1ad791fb54ddf57575e3d01b95558fb4a6153 

I'll make some more tweaks to make sure paying customers are still synced event if they haven't technically been logged out/in in over a month.

**Comment by bajtos** [comment]
@andrew I confirm it's working again now, thank you for a quick response! I really appreciate the time and effort you are putting into running Octobox ❤️

**Comment by pradyunsg** [comment]
I think we can close this now?
