### ISSUE TITLE
Feature request: visual indication of some status changes (merges, assignments, etc.)

### ISSUE THREAD

**Issue by terminalmage** [octobox/octobox#567]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**
Octobox makes an pull request "unread" when all that happened was that it was merged. Assuming that Octobox is supposed to make going through your notifications less of a hassle, this works _against_ that goal. At least when viewing https://github.com/notifications, a PR will show a different color noting that it was merged.

Moreover, if an issue which has already been tagged with something like `Subscribed` or `Team Mention` is assigned to you, Octobox doesn't change the categorization (or add a secondary category for the issue). If I know an issue is only "updated" because it was assigned to me, then it may be higher (or lower) priority based on that knowledge, but Octobox doesn't provide a way for me to know.

🎯 **Goal**
Better categorization of issues

**Comment by chrisarcand** [comment]
> Octobox makes an pull request "unread" when all that happened was that it was merged. Assuming that Octobox is supposed to make going through your notifications less of a hassle, this works against that goal. 

I think that's a subjective opinion. I for one like to know when long-standing PRs are merged; it's an activity that happened that I haven't read yet, thus it is unread. However, a feature to be able to specify that you don't want them to be marked as read for only merges seems totally appropriate!

> At least when viewing https://github.com/notifications, a PR will show a different color noting that it was merged. 

This is [already a feature](https://github.com/octobox/octobox/pull/411); it is not available on octobox.io however. Please [see the README](https://github.com/octobox/octobox#octoboxio). 

> Moreover, if an issue which has already been tagged with something like Subscribed or Team Mention is assigned to you, Octobox doesn't change the categorization

Octobox relies 100% on what is provided by GitHub for notification reasons. From the [GitHub API documentation](https://developer.github.com/v3/activity/notifications/#notification-reasons):

> Note that the reason is modified on a per-thread basis, and can change, if the reason on a later notification is different.

> For example, if you are the author of an issue, subsequent notifications on that issue will have a reason of author. If you're then @mentioned on the same issue, the notifications you fetch thereafter will have a reason of mention. The reason remains as mention, regardless of whether you're ever mentioned again.

I also have opinions about why that's sort of silly, but alas, that's how the data is provided. To change this behavior in Octobox might be nice, but I also think that the logic involved in maintaining semantics between what Octobox infers and what GitHub provides might be fairly messy.

As the main purpose of the issue was referring to visual indication of status changes and the rest is entirely dependent on GitHub's API, I'm going to go ahead and close this. Thanks!
