### ISSUE TITLE
Only show mention badge on an issue for unread mentions

### ISSUE THREAD

**Issue by betatim** [octobox/octobox#739]
🐞 **Problem**
Can't tell if there is new chatter or if you were @-ed on an issue or PR in which you've been previously @-ed.

🎯 **Goal**
Change the notification view so that the "Mention" badge only appears if you were mentioned within the "as yet unread" messages. Otherwise issues/PRs where there is activity without mentioning you show the badge for that type of activity.

Will require data added in #709 to implement.

**Comment by andrew** [comment]
👍 this will be really helpful for people involved in a number of big/long/active threads

#709 will enable us to see the individual comments on threadview that are new since the last time you read(viewed) it, then we can scan the comment body for the `@username` of the owner of the notification

Team mentions will be more difficult as octobox doesn't currently know which teams you're part of, so we'll skip that until https://github.com/octobox/octobox/issues/660 is resolved

**Comment by Zimmi48** [comment]
In fact, the "reason" field which is provided by GitHub is very often unhelpful, even more so when more information is coming thanks to the "App" features. For instance, filtering by "Assigned" or "Assigned to you" is redundant except the second one will be more accurate ("Open" / "Merged" / "Closed" is also more specific than "State change"). Similarly, there could be filters "Authored by you" / "Commented by you" / "You were mentioned" / "Your review was requested" which would make the other reason filters redundant (and this should actually already be possible to setup with pinned searches). Even if this wouldn't solve the problem mentioned in this issue (because once you were mentioned, there is no going back), relying on these filters instead of the "reason" field for repos where the "App" features are available would at least have the good effect of solving the very similar problem with "Review requested" (it annoys me a lot that when I removed myself from the review request list or when I provided the requested review, I still see this as the reason for the notification and I don't know if someone requested a review again).

**Comment by Zimmi48** [comment]
I have changed my mind on the usefulness of the "reason" field since I have found a workaround to make it go back to some default: I go to the issue / PR, and I click "Unsubscribe" and then "Subscribe". The reason goes back from "Mentioned" or "Review Requested" to "Manual". I am still missing two things: a simple button in Octobox that would automate this process, and the "Manual" color being changed to use the same one (purple) as the "Subscribed" color (or this being configurable).

The advantage of this process is that I'm the one who decides when a "Review request" or a "Mention" has been treated, even if the notification has been read already (or even sometimes "Archived").
