### ISSUE TITLE
Add "clear archive" functionality

### ISSUE THREAD

**Issue by BPScott** [octobox/octobox#848]
🐞 **Problem**

Feature request: I have lots of archived notifications that I'm never going to read again. It'd be nice if I could purge the contents of my archive  rather than have an ever-growing number of notifications in there.

Stealing from the "file deletion in your OS" metaphor: "to archive" is "to send to the trash" but there's currently not equivalent metaphor for "empty the trash".

🎯 **Goal**

Removing noise in the archive by letting you cull its contents.

💡 **Possible solutions**

An "Delete" button that shows next to "Unarchive selected" when you select notifications in the Archive view

**Comment by andrew** [comment]
Archive in Octobox is more akin to archive in Gmail, to get things out of the email but not remove it completely as it could be useful later in search.

Gmail also has a delete function for things you don't to keep in the archive, only potential issue we have is if you delete a recent notification with an actual sql DELETE then octobox would recreate the notification record on the next sync, so we'd likely want to set a `deleted_at` timestamp so as to avoid that.

One related thing would be, what happens if there's new activity on a notification thread you deleted, do you expect to hear from it again? Because they will still show up in the GitHub Notifications dashboard, so probably like with email, if you delete an email, later replies should still appear in your inbox, as apposed to marking something as spam, which you'd expect to never see it again.

**Comment by pradyunsg** [comment]
I think it'd be sensible to automatically delete archived notifications older than X, perhaps letting X be configurable?

**Comment by BPScott** [comment]
I like following the gmail metaphor for this, it correlates a little better than the file-system idea.

> One related thing would be, what happens if there's new activity on a notification thread you deleted, do you expect to hear from it again?

I would say yes, I agree with your flow. Deleting a notification thread, then having a new addition to that thread would result in new messages appearing in the inbox. I believe this is the same as what happens when new notifications appear on an archived but not muted notification thread.

**Comment by andrew** [comment]
>  I believe this is the same as what happens when new notifications appear on an archived but not muted notification thread.

Yeah archived notifications that have new activity get bumped back into the inbox. 

For muted notifications (called "unsubscribe" on the github side), I seem to remember that you won't see further updates UNLESS you get directly @mentioned again in that thread, except if you explicitly "ignore" the whole repository.

**Comment by andrew** [comment]
@pradyunsg part of the value in having the archive is being able to search and filter old notifications, something which isn't possible to do with GitHub notifications as read ones disappear after a certain amount of time, so deleting old ones automatically in Octobox isn't something I'd encourage.

**Comment by BenJam** [comment]
Closing in favour of #882 as it seems like a good compromise between the two views here.

**Comment by andrew** [comment]
Deploying https://github.com/octobox/octobox/pull/987 to https://octobox.io now, delete buttons are accessible from the Archived view :shipit:
